### PR TITLE
Extend go-releaser builds for arm architectures

### LINKED ISSUE #831: chore: add support for ARM architectures
**What steps did you take and what happened:**

Currently deploying the starboard operator on ARM instances is not working (e.g. Graviton AWS EC2)

On start :
```
standard_init_linux.go:228: exec user process caused: exec format error
```

This error is a known symptom of not supported arm architecture.

**What did you expect to happen:**

Operator starting.

**Anything else you would like to add:**

Blocked on operator deployment, I have not checked on tools used by Starboard if the same issue will happen (kube bench, trivy, polaris, ...)

**Environment:**

- Starboard version (use `starboard version`): 0.13.0
- Kubernetes version (use `kubectl version`): 1.22
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): EKS 1.21, Graviton t4g, Bottlerocket OS

### PR DESCRIPTION
**Pull request by jlamande**
Fixes #831

### CODE REVIEW

**Comment by jlamande** [comment]
@chen-keinan any idea why the coverage is lower after your last merge of main branch ? :/

**Comment by danielpacak** [comment]
> @chen-keinan any idea why the coverage is lower after your last merge of main branch ? :/

CodeCov is infamous for reporting slightly different coverage even if the relevant code hasn't changed. I don't see any reasonable explanation to that. Probably some rounding errors on their server 🤓 Hopefully they don't do the same for monetary calculations when you use paid CodeCov plans 💰

**Review by danielpacak — CHANGES_REQUESTED** [review]
I believe we must also add / update `docker` and `docker_manifests` config in `.goreleaser.yaml` to publish multi-platform images to DockerHub and ECR Gallery. So far we just added ARM architecture to build matrix for Starboard CLI and Starboard Operator executable binaries.

See https://goreleaser.com/customization/docker_manifest/ for more details.

You can see how it's configured for Trivy on https://github.com/aquasecurity/trivy/blob/main/goreleaser.yml#L94 and published to DockerHub on https://hub.docker.com/layers/aquasec/trivy/0.22.0/images/sha256-a938728e0d370e605c20d34790f60f636d63e591bedd9fbf0286762bcf1d970b?context=explore

> TIP To test things out [install](https://goreleaser.com/install/) GoReleaser and build unversioned snapshot with
> ```
> goreleaser release --snapshot --skip-publish --rm-dist
> ```

**Comment by danielpacak** [comment]
Closing as @chen-keinan took this task over in #958 .

**Pull request closed without merging**
