### PR TITLE
update description

### PR DESCRIPTION
**Pull request by chen-keinan**
update starboard operation description 
Signed-off-by: chenk <hen.keinan@gmail.com>

### CODE REVIEW

**Review by danielpacak — CHANGES_REQUESTED** [review]
Instead of changing single words or sentences I think we should do a holistic review of the README.md and the front page of the documentation based on the current roadmap and feedback collected by @AnaisUrlichs 

In particular:
- [ ] Diminish the importance of plugins and extensibility and focus on security scanning 
- [ ] Update status on integrations with other projects (e.g. Octant)
- [ ] Remove / update the ROADMAP.md
- [ ] Deprecate Polaris and Conftest plugins and focus on built-in configuration checker powered by defsec rules (add examples and tutorials)

I'd target v0.16.0 with such big changes. In v0.15.0 our focus is efficient configuration auditing and NSA compliance so I'd update only what's absolutely necessary. /cc @itaysk

**Comment by chen-keinan** [comment]
I agree documentation changes can be done incrementally to be targeted to v0.16.0.

**Comment by chen-keinan** [comment]
closing, will create a separate PR for updateding description on straboard operation.

**Comment by AnaisUrlichs** [comment]
What do you think about listing installation options in the README? Half of the people will look in the README for installation and will only later consider opening the docs and the other half goes straight to the docs

**Comment by danielpacak** [comment]
> What do you think about listing installation options in the README? Half of the people will look in the README for installation and will only later consider opening the docs and the other half goes straight to the docs

One big problem with installation steps in README is that they're not versioned. Compare how we install Starboard v0.14.1 and v0.15.0. We can do our best to maintain documentation with installation steps and links pinned to particular version, but I'm not sure about README.

**Pull request closed without merging**
