### PR TITLE
chore: test the helm chart in the PR

### PR DESCRIPTION
**Pull request by krol3**
- Run the testing helm chart in the PR (only 'deploy/helm/**')
- Separate the release chart in another job.

### CODE REVIEW

**Comment by krol3** [comment]
@danielpacak please validate the idea of test the manifest of the helm in the PR, if make sense.

**Review by danielpacak — CHANGES_REQUESTED** [review]
Thank you for working on this @krol3 ! I think it's great idea to test the Helm chart as part of our build pipeline.

We have already grouped all checks related to pull requests in a single file called `.github/worflow/build.yaml` so I'd add such job in there and run it after all integration tests passed for few reasons:
- If tests fail we gonna restart build anyway so doing all these Helm checks would be wasteful.
  starboard-ci-workflow
- Maybe not in scope of this PR but ... after creating a Helm release it would be very nice to run actual integration tests to see the the operator deployed with Helm really works (not just that Helm release was created).
- We'd like to get rid of the `workflow_dispatch` event and publish to Helm repository (and MkDocs) when the release workflow is complete.

**Comment by krol3** [comment]
@danielpacak the "Test Helm Chart" was moved to the build job.

**Review by danielpacak — APPROVED** [review]
Thanks for working on this @krol3 I just slightly updated the workflow to run Helm chart tests only after integration tests passed (as originally suggested) 🍀 🌏 .

**Pull request merged**
