### PR TITLE
trivy: cs mode need mount docker.sock

### PR DESCRIPTION
**Pull request by fengshunli**
trivy: cs mode need mount docker.sock

### CODE REVIEW

**Review by danielpacak — COMMENTED** [review]
:wave: @fengshunli Could you elaborate why you needed dockersock mount please? AFAIK Trivy server can pull images without Docker daemon. What's more, K8s may use different container runtime, in which case your patch won't work.

**Comment by danielpacak** [comment]
If it's still relevant please follow contributing guide https://github.com/aquasecurity/starboard/blob/main/CONTRIBUTING.md#issues-and-discussions

**Comment by fengshunli** [comment]
cs remote access error prompt
image
image

mount /var/run/docker.sock show good
image
@danielpacak

**Comment by fengshunli** [comment]
The cache file I mounted, docker access local image, need  /var/run/docker.sock to communicate  @danielpacak

**Comment by danielpacak** [comment]
Not sure what you're doing @fengshunli Where did you mount the /var/run/docker.sock? To the starboard operator pod?

**Comment by fengshunli** [comment]
To access the local image via the trivy client job started by the pod, you need to mount /var/run/docker.sock  @danielpacak

**Comment by danielpacak** [comment]
Okey so please be more specific about your scenarios. I though we were talking about officially supported version that has been tested and released. To troubleshoot a custom changes in code please share at least a Git branch so we can see what you did in code.

**Pull request closed without merging**
