### PR TITLE
feat: helm chart

### PR DESCRIPTION
**Pull request by krol3**
Issue [187](https://github.com/aquasecurity/starboard/issues/187) - create helm chart for starboard

### CODE REVIEW

**Comment by consideRatio** [comment]
Hi @krol3!

We ended up working in parallel on creating a Helm chart (https://github.com/aquasecurity/starboard-operator/pull/53), so I'm now looking to hear your thoughts on the situation.

If you wan't, I'd be happy to either act as a PR author where your review would be warmly welcome, or provide you with review help in your PR if you would like it. No matter what, I'd also want to welcome you to do nothing or anything with the code added in https://github.com/aquasecurity/starboard-operator/pull/53.

Cheers from Sweden!

**Comment by krol3** [comment]
Hi @consideRatio , I'll review your PR, :)

**Comment by consideRatio** [comment]
Awesome @krol3 okay! :tada: I opened #204 in this repo.

**Comment by krol3** [comment]
Closing the PR, already other PR with the same issue.

**Pull request closed without merging**
