### PR TITLE
add TRIVY_NON_SSL config and environment variable

### PR DESCRIPTION
**Pull request by elchenberg**
I had to scan images of an internal registry without SSL/TLS and I was able to do it with these changes.

<details>

**Edit: Turns out the following is completely unrelated to starboard or this pull request.**

But I see a lot of the following errors in the logs and I don't know if they are related:

```json
{
  "level": "error",
  "ts": 1639496503.9841638,
  "logger": "controller.cronjob",
  "msg": "Reconciler error",
  "reconciler group": "batch",
  "reconciler kind": "CronJob",
  "name": "my-name",
  "namespace": "my-namespace",
  "error": "getting secret by name: my-namespace/registry-login: Secret \"registry-login\" not found",
  "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/elchenberg/.go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:227"
}
```
</details>

### CODE REVIEW

**Comment by danielpacak** [comment]
> I had to scan images of an internal registry without SSL/TLS and I was able to do it with these changes.
> 
> But I see a lot of the following errors in the logs and I don't know if they are related:
> 
> ```json
> {
>   "level": "error",
>   "ts": 1639496503.9841638,
>   "logger": "controller.cronjob",
>   "msg": "Reconciler error",
>   "reconciler group": "batch",
>   "reconciler kind": "CronJob",
>   "name": "my-name",
>   "namespace": "my-namespace",
>   "error": "getting secret by name: my-namespace/registry-login: Secret \"registry-login\" not found",
>   "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/elchenberg/.go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:227"
> }
> ```

👋 @elchenberg Thank you for working on this enhancements. Before we jump on review, could you explain how is this error message related to Trivy and registry SSH?

It seems that you probably used imagePullSecret ref (registry-login) in your deployment descriptor, whereas such secret does not exist in the my-namespace namespace. Could you also confirm that this workload is running and the secret is of type registry credentials?

**Comment by elchenberg** [comment]
> Before we jump on review, could you explain how is this error message related to Trivy and registry SSH?
> 
> It seems that you probably used imagePullSecret ref (registry-login) in your deployment descriptor, whereas such secret does not exist in the my-namespace namespace. Could you also confirm that this workload is running and the secret is of type registry credentials?

My bad. Turns out, there are some outdated deployments with imagePullSecrets. :facepalm: The imagePullSecret ref was my first assumption, too! But instead of checking it, I thought I **knew** that we were not using any imagePullSecrets in our cluster. And then I jumped to the conclusion that it might be a problem with starboard. :see_no_evil: Sorry for that!

**Comment by danielpacak** [comment]
> > Before we jump on review, could you explain how is this error message related to Trivy and registry SSH?
> > It seems that you probably used imagePullSecret ref (registry-login) in your deployment descriptor, whereas such secret does not exist in the my-namespace namespace. Could you also confirm that this workload is running and the secret is of type registry credentials?
> 
> My bad. Turns out, there are some outdated deployments with imagePullSecrets. 🤦 The imagePullSecret ref was my first assumption, too! But instead of checking it, I thought I **knew** that we were not using any imagePullSecrets in our cluster. And then I jumped to the conclusion that it might be a problem with starboard. 🙈 Sorry for that!

I got it and I'm glad you sorted it out.

Having said  that, do you still need the functionality implemented in this PR? If yes, could you share the error with stack trace so we can confirm that TLS certificate verification is the root cause of the problem that you are trying to fix with this patch?

Also please sign the CLA and consider adding unit tests for any new functionality in Trivy plugin, which are anyway required before we can proceed with your PR.

**Comment by elchenberg** [comment]
Yes, I still need the functionality. :slightly_smiling_face: 

#### Regarding: Stack Trace

My internal container registry (https://hub.docker.com/_/registry) is running in a "registry" namespace. It has no SSL/TLS and does not require authentication.

I deploy Starboard Operator using the Helm chart v0.8.2 with the following configuration:

```yaml
operator:
  configAuditScannerEnabled: false
  kubernetesBenchmarkEnabled: false
  vulnerabilityScannerEnabled: true
targetNamespaces: ""
trivy:
  ignoreUnfixed: "true"
  mode: ClientServer
  resources:
    limits:
      memory: 1000M
  serverURL: "http://trivy.{{ .Release.Namespace }}.svc:4954"
  severity: HIGH,CRITICAL
```

Trivy is installed in the same namespace from the Triviy Helm chart v0.4.8 with the following configuration:

```yaml
image:
  tag: 0.21.3
```

With all images from the internal registry (registry.registry.svc:5000) I get the following error message and stack trace:

```txt
2021-12-21T11:11:20.854Z	FATAL	scanner initialize error: unable to initialize the docker scanner: 3 errors occurred:
	* unable to inspect the image (registry.registry.svc:5000/image-name:image-tag): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
	* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory
	* Get "https://registry.registry.svc:5000/v2/": http: server gave HTTP response to HTTPS client

sigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/reconcile/reconcile.go:102
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:227
```

#### Regarding: Unit Tests

I will try my best but all I did so far was to copy and paste the `appendTrivyInsecureEnv` and `GetInsecureRegistries` functions so I do not know if I will be able to write proper tests.

**Review by chen-keinan — APPROVED** [review]
@elchenberg Great job! code and tests are looking good

**Comment by elchenberg** [comment]
@chen-keinan Thank you! It was a pleasure.

**Pull request merged**
