### PR TITLE
Modified Decode() to use SplitN rather than Split

### LINKED ISSUE #857: Support Service Account Keys defined in ImagePullSecrets
**What steps did you take and what happened:**

We're using Google Artifact Registry to host our containers.

We have configured the access according to the Google Documentation: https://cloud.google.com/artifact-registry/docs/access-control

So we're using Service Account keys in our ImagePullSecrets. ImagePullSecrets would look like this (SA_KEY is encoded): 

```
{
  "auths": {
    "repository_name": {
      "username": "_json_key_base64",
      "password": "SA_KEY"
    }
  }
}
```

Decoded SA_KEY would look like

```
{
  "type": "service_account",
  "project_id": "XYZ",
  "private_key_id": "XYZ",
  "private_key": "XYZ",
  "client_email": "XYZ@XYZ",
  "client_id": "XYZ",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "XYZ"
}
```

When Vulnerability Scan tries to Pull the image for scanning it gives out error:

`"error":"reading .dockerconfigjson field of \"APPLICATION_NAME/image-pull-secrets\" secret: expected username and password concatenated with a colon (:)","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:227"}`

https://github.com/aquasecurity/starboard/blob/8944e54abf1edb1df80ce0a8f6d91b8784c05a35/pkg/docker/config.go#L26-L36

Is splitting the string with `:` and giving out errors if `len(split) != 2`. As the SA_KEY has multiple `:` included in the string, it gives out the error and breaks ImagePull

**What did you expect to happen:**

To be able to use Service Account keys in ImagePullSecrets.

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Starboard version (use `starboard version`): 0.13.1 (starboard-operator)
- Kubernetes version (use `kubectl version`): v1.20.10-gke.1600
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): N/A

### PR DESCRIPTION
**Pull request by jessequinn**
Modified Decode() in docker config pkg to use SplitN rather than Split. This allows GCR auths to be split that contain multiple : characters.

## Related issues
- Close #857

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/aquasecurity/starboard/blob/main/CONTRIBUTING.md) to this repository.
- [x] I've added tests that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by chen-keinan** [comment]
@jessequinn were you able to build the image and load it via kind?

**Comment by jessequinn** [comment]
> @jessequinn were you able to build the image and load it to kind?

yes.

**Comment by chen-keinan** [comment]
> > @jessequinn were you able to build the image and load it to kind?
> 
> yes. however, the image will not contain this change. building the image uses github directly from what i remember.

 `make docker-build` will build it locally and create the following image:`aquasec/starboard-operator:dev` 
  
Is this what you used?

**Comment by jessequinn** [comment]
> > > @jessequinn were you able to build the image and load it to kind?
> > 
> > 
> > yes. however, the image will not contain this change. building the image uses github directly from what i remember.
> 
> `make docker-build` will build it locally and create the this image:`aquasec/starboard-operator:dev`
> 
> Is this what you used?

yes. verbatim to the contribution info page.

**Comment by chen-keinan** [comment]
I see, it should work , I'll check it myself now

**Comment by jessequinn** [comment]
considering the change is so small why would it not work?

**Comment by chen-keinan** [comment]
> considering the change is so small, why would it not work?

I agree it should be ok, will do a quick check. please rebase your branch with upstream in meanwhile

**Comment by chen-keinan** [comment]
LGTM!, thank you for the contribution, please rebase your branch with upstream

**Review by chen-keinan — APPROVED** [review]

**Pull request merged**
