### PR TITLE
Bump up the z version for kube-bench (0.3.0 -> 0.3.1)

### PR DESCRIPTION
**Pull request by krisctl**
Fix for https://github.com/aquasecurity/starboard/issues/115

### CODE REVIEW

**Comment by krisctl** [comment]
Thanks for reviewing, @danielpacak!

You are right about the failing test. I missed running the test locally and saw only when it failed the checks. I will work on updating the converter code to support 0.3.1 of kube-bench.

**Review by danielpacak — CHANGES_REQUESTED** [review]
Hi @krisctl Please rebase your PR so it includes only the commit with the actual change to kube-bench 0.3.1

**Comment by krisctl** [comment]
> Hi @krisctl Please rebase your PR so it includes only the commit with the actual change to kube-bench 0.3.1

Thanks, @danielpacak, I believe the changes should now only show the things that I have worked on. Pardon my unfamiliarity with Git workflows!

**Review by danielpacak — CHANGES_REQUESTED** [review]
No worries @krisctl with Git workflows! It's not always intuitive, but you'll get there. Anyway, I can see 14 commits on the PR branch, which means that it hasn't been rebased. You might want to sync your fork as explained in https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

And usually it's easier to open a PR from the feature branch rather than the master branch of your fork and then perform interactive rebase if needed https://docs.github.com/en/github/using-git/about-git-rebase

**Comment by krisctl** [comment]
Hi @danielpacak, I have been trying this for some time now. I believe it would be better that I close this PR for now and open up a new one with the feature branch as you had mentioned (and also probably learn Git a bit more). Thanks for your time on this and please stay tuned for another PR for this.

**Pull request closed without merging**
